# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NameSet.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='NameSet.proto',
  package='NameSet',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rNameSet.proto\x12\x07NameSet\")\n\x07NameSet\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\r\n\x05names\x18\x02 \x03(\tb\x06proto3')
)




_NAMESET = _descriptor.Descriptor(
  name='NameSet',
  full_name='NameSet.NameSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='NameSet.NameSet.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='names', full_name='NameSet.NameSet.names', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=67,
)

DESCRIPTOR.message_types_by_name['NameSet'] = _NAMESET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NameSet = _reflection.GeneratedProtocolMessageType('NameSet', (_message.Message,), dict(
  DESCRIPTOR = _NAMESET,
  __module__ = 'NameSet_pb2'
  # @@protoc_insertion_point(class_scope:NameSet.NameSet)
  ))
_sym_db.RegisterMessage(NameSet)


# @@protoc_insertion_point(module_scope)
