# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Request.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rRequest.proto\x12\x0eprotoc.Request\x1a\x19google/protobuf/any.proto\".\n\x07Request\x12#\n\x05items\x18\x01 \x03(\x0b\x32\x14.google.protobuf.Any\"K\n\x08Sequence\x12\x11\n\tdirection\x18\x03 \x01(\x08\x12\x0c\n\x04info\x18\x01 \x01(\x08\x12\x0c\n\x04line\x18\x02 \x01(\t\x12\x10\n\x08sequence\x18\x04 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Request_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=60
  _REQUEST._serialized_end=106
  _SEQUENCE._serialized_start=108
  _SEQUENCE._serialized_end=183
# @@protoc_insertion_point(module_scope)
