# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Response.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Response.proto',
  package='protoc.Response',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0eResponse.proto\x12\x0fprotoc.Response\x1a\x19google/protobuf/any.proto\"/\n\x08Response\x12#\n\x05items\x18\x01 \x03(\x0b\x32\x14.google.protobuf.Any\"#\n\x04Time\x12\r\n\x05\x65\x61rly\x18\x01 \x01(\t\x12\x0c\n\x04late\x18\x02 \x01(\t\";\n\x05Route\x12#\n\x04time\x18\x01 \x01(\x0b\x32\x15.protoc.Response.Time\x12\r\n\x05names\x18\x02 \x03(\t\"<\n\x04Info\x12\x0c\n\x04name\x18\x01 \x01(\t\x12&\n\x06routes\x18\x02 \x03(\x0b\x32\x16.protoc.Response.Route\"M\n\x0bMonitorItem\x12\x0f\n\x07vehicle\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x04 \x01(\r\x12\r\n\x05stops\x18\x02 \x01(\r\x12\x10\n\x08\x64istance\x18\x03 \x01(\r\"-\n\x0c\x44ispatchItem\x12\x0f\n\x07vehicle\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\t\"[\n\x07Monitor\x12#\n\x04info\x18\x01 \x01(\x0b\x32\x15.protoc.Response.Info\x12+\n\x05items\x18\x02 \x03(\x0b\x32\x1c.protoc.Response.MonitorItem\"]\n\x08\x44ispatch\x12#\n\x04info\x18\x01 \x01(\x0b\x32\x15.protoc.Response.Info\x12,\n\x05items\x18\x02 \x03(\x0b\x32\x1d.protoc.Response.DispatchItem\"=\n\x05\x45rror\x12#\n\x04info\x18\x01 \x01(\x0b\x32\x15.protoc.Response.Info\x12\x0f\n\x07message\x18\x02 \x01(\tb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='protoc.Response.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='protoc.Response.Response.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=109,
)


_TIME = _descriptor.Descriptor(
  name='Time',
  full_name='protoc.Response.Time',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='early', full_name='protoc.Response.Time.early', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='late', full_name='protoc.Response.Time.late', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=146,
)


_ROUTE = _descriptor.Descriptor(
  name='Route',
  full_name='protoc.Response.Route',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='protoc.Response.Route.time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='names', full_name='protoc.Response.Route.names', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=207,
)


_INFO = _descriptor.Descriptor(
  name='Info',
  full_name='protoc.Response.Info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='protoc.Response.Info.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='routes', full_name='protoc.Response.Info.routes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=269,
)


_MONITORITEM = _descriptor.Descriptor(
  name='MonitorItem',
  full_name='protoc.Response.MonitorItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vehicle', full_name='protoc.Response.MonitorItem.vehicle', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='protoc.Response.MonitorItem.time', index=1,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stops', full_name='protoc.Response.MonitorItem.stops', index=2,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='distance', full_name='protoc.Response.MonitorItem.distance', index=3,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=271,
  serialized_end=348,
)


_DISPATCHITEM = _descriptor.Descriptor(
  name='DispatchItem',
  full_name='protoc.Response.DispatchItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vehicle', full_name='protoc.Response.DispatchItem.vehicle', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='protoc.Response.DispatchItem.time', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=350,
  serialized_end=395,
)


_MONITOR = _descriptor.Descriptor(
  name='Monitor',
  full_name='protoc.Response.Monitor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='protoc.Response.Monitor.info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='items', full_name='protoc.Response.Monitor.items', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=397,
  serialized_end=488,
)


_DISPATCH = _descriptor.Descriptor(
  name='Dispatch',
  full_name='protoc.Response.Dispatch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='protoc.Response.Dispatch.info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='items', full_name='protoc.Response.Dispatch.items', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=490,
  serialized_end=583,
)


_ERROR = _descriptor.Descriptor(
  name='Error',
  full_name='protoc.Response.Error',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='protoc.Response.Error.info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='protoc.Response.Error.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=585,
  serialized_end=646,
)

_RESPONSE.fields_by_name['items'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_ROUTE.fields_by_name['time'].message_type = _TIME
_INFO.fields_by_name['routes'].message_type = _ROUTE
_MONITOR.fields_by_name['info'].message_type = _INFO
_MONITOR.fields_by_name['items'].message_type = _MONITORITEM
_DISPATCH.fields_by_name['info'].message_type = _INFO
_DISPATCH.fields_by_name['items'].message_type = _DISPATCHITEM
_ERROR.fields_by_name['info'].message_type = _INFO
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['Time'] = _TIME
DESCRIPTOR.message_types_by_name['Route'] = _ROUTE
DESCRIPTOR.message_types_by_name['Info'] = _INFO
DESCRIPTOR.message_types_by_name['MonitorItem'] = _MONITORITEM
DESCRIPTOR.message_types_by_name['DispatchItem'] = _DISPATCHITEM
DESCRIPTOR.message_types_by_name['Monitor'] = _MONITOR
DESCRIPTOR.message_types_by_name['Dispatch'] = _DISPATCH
DESCRIPTOR.message_types_by_name['Error'] = _ERROR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'Response_pb2'
  # @@protoc_insertion_point(class_scope:protoc.Response.Response)
  ))
_sym_db.RegisterMessage(Response)

Time = _reflection.GeneratedProtocolMessageType('Time', (_message.Message,), dict(
  DESCRIPTOR = _TIME,
  __module__ = 'Response_pb2'
  # @@protoc_insertion_point(class_scope:protoc.Response.Time)
  ))
_sym_db.RegisterMessage(Time)

Route = _reflection.GeneratedProtocolMessageType('Route', (_message.Message,), dict(
  DESCRIPTOR = _ROUTE,
  __module__ = 'Response_pb2'
  # @@protoc_insertion_point(class_scope:protoc.Response.Route)
  ))
_sym_db.RegisterMessage(Route)

Info = _reflection.GeneratedProtocolMessageType('Info', (_message.Message,), dict(
  DESCRIPTOR = _INFO,
  __module__ = 'Response_pb2'
  # @@protoc_insertion_point(class_scope:protoc.Response.Info)
  ))
_sym_db.RegisterMessage(Info)

MonitorItem = _reflection.GeneratedProtocolMessageType('MonitorItem', (_message.Message,), dict(
  DESCRIPTOR = _MONITORITEM,
  __module__ = 'Response_pb2'
  # @@protoc_insertion_point(class_scope:protoc.Response.MonitorItem)
  ))
_sym_db.RegisterMessage(MonitorItem)

DispatchItem = _reflection.GeneratedProtocolMessageType('DispatchItem', (_message.Message,), dict(
  DESCRIPTOR = _DISPATCHITEM,
  __module__ = 'Response_pb2'
  # @@protoc_insertion_point(class_scope:protoc.Response.DispatchItem)
  ))
_sym_db.RegisterMessage(DispatchItem)

Monitor = _reflection.GeneratedProtocolMessageType('Monitor', (_message.Message,), dict(
  DESCRIPTOR = _MONITOR,
  __module__ = 'Response_pb2'
  # @@protoc_insertion_point(class_scope:protoc.Response.Monitor)
  ))
_sym_db.RegisterMessage(Monitor)

Dispatch = _reflection.GeneratedProtocolMessageType('Dispatch', (_message.Message,), dict(
  DESCRIPTOR = _DISPATCH,
  __module__ = 'Response_pb2'
  # @@protoc_insertion_point(class_scope:protoc.Response.Dispatch)
  ))
_sym_db.RegisterMessage(Dispatch)

Error = _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), dict(
  DESCRIPTOR = _ERROR,
  __module__ = 'Response_pb2'
  # @@protoc_insertion_point(class_scope:protoc.Response.Error)
  ))
_sym_db.RegisterMessage(Error)


# @@protoc_insertion_point(module_scope)
