# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Response.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eResponse.proto\x12\x0fprotoc.Response\x1a\x19google/protobuf/any.proto\"/\n\x08Response\x12#\n\x05items\x18\x01 \x03(\x0b\x32\x14.google.protobuf.Any\"#\n\x04Time\x12\r\n\x05\x65\x61rly\x18\x01 \x01(\t\x12\x0c\n\x04late\x18\x02 \x01(\t\";\n\x05Route\x12#\n\x04time\x18\x01 \x01(\x0b\x32\x15.protoc.Response.Time\x12\r\n\x05names\x18\x02 \x03(\t\"<\n\x04Info\x12\x0c\n\x04name\x18\x01 \x01(\t\x12&\n\x06routes\x18\x02 \x03(\x0b\x32\x16.protoc.Response.Route\"M\n\x0bMonitorItem\x12\x0f\n\x07vehicle\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x04 \x01(\r\x12\r\n\x05stops\x18\x02 \x01(\r\x12\x10\n\x08\x64istance\x18\x03 \x01(\r\"-\n\x0c\x44ispatchItem\x12\x0f\n\x07vehicle\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\t\"[\n\x07Monitor\x12#\n\x04info\x18\x01 \x01(\x0b\x32\x15.protoc.Response.Info\x12+\n\x05items\x18\x02 \x03(\x0b\x32\x1c.protoc.Response.MonitorItem\"]\n\x08\x44ispatch\x12#\n\x04info\x18\x01 \x01(\x0b\x32\x15.protoc.Response.Info\x12,\n\x05items\x18\x02 \x03(\x0b\x32\x1d.protoc.Response.DispatchItem\"=\n\x05\x45rror\x12#\n\x04info\x18\x01 \x01(\x0b\x32\x15.protoc.Response.Info\x12\x0f\n\x07message\x18\x02 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Response_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESPONSE._serialized_start=62
  _RESPONSE._serialized_end=109
  _TIME._serialized_start=111
  _TIME._serialized_end=146
  _ROUTE._serialized_start=148
  _ROUTE._serialized_end=207
  _INFO._serialized_start=209
  _INFO._serialized_end=269
  _MONITORITEM._serialized_start=271
  _MONITORITEM._serialized_end=348
  _DISPATCHITEM._serialized_start=350
  _DISPATCHITEM._serialized_end=395
  _MONITOR._serialized_start=397
  _MONITOR._serialized_end=488
  _DISPATCH._serialized_start=490
  _DISPATCH._serialized_end=583
  _ERROR._serialized_start=585
  _ERROR._serialized_end=646
# @@protoc_insertion_point(module_scope)
